controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    robot_base_control:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
/**/robot_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["left_back_wheel_joint", "left_front_wheel_joint", "left_mid_wheel_joint"]
    right_wheel_names: ["right_back_wheel_joint", "right_front_wheel_joint", "right_mid_wheel_joint"]
    wheel_separation: 1.90
    wheel_radius: 0.30
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0
    # Base frame_id
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0     
    
/**/scara_controller:
  ros__parameters:
    joints:
      - first_bone_joint
      - second_bone_joint
      - third_bone_joint
      - base_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true

/**/gripper_controller:
  ros__parameters:
    joints:
      - gripper_1_joint
      - gripper_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
