# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - first_bone_joint
      - second_bone_joint
      - third_bone_joint
      - base_gripper_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_1_joint
      - gripper_2_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true